# Task Definitions
trending_topic_search_task:
  description: >
    topic: {topic}
    current_year: {current_year}
    ###
    Search for the latest trending topics related to AI, ML, CS, and other user-defined topics.
    Use web scraping tools and APIs to fetch the most relevant and up-to-date content from trusted sources like Google News, Reddit, and Twitter.
  expected_output: >
    A list of trending topics with relevant metadata (e.g., title, URL, snippet, engagement metrics).
  agent: trending_topic_searcher

trend_relevance_verification_task:
  description: >
    current_year: {current_year}
    ###
    Verify the relevance and quality of the fetched trending topics using AI-based classification or sentiment analysis.
    Ensure that the topics are aligned with the user's interests and current trends.
  expected_output: >
    A filtered list of the most relevant and high-quality trending topics.
  agent: trend_relevance_verifier

content_structuring_task:
  description: >
    current_year: {current_year}
    ###
    Take the trending topics and generate structured ideas for posts and polls.
    For each topic, create a post idea (hook, outline, engagement strategy) and a poll idea (question, options).
  expected_output: >
    A list of structured ideas for both posts and polls based on trending topics.
    Each item should include:
      - Post Title
      - Post Hook
      - Post Outline
      - Poll Question
      - Poll Options
  agent: content_structurer

engagement_optimization_task:
  description: >
    current_year: {current_year}
    ###
    Optimize the generated post and poll content for maximum engagement based on social media performance analytics.
    Suggest changes to content structure, hooks, and other elements to improve engagement.
  expected_output: >
    An optimized version of the post and poll content, with suggestions for better engagement.
  agent: engagement_optimizer

seo_optimization_task:
  description: >
    current_year: {current_year}
    ###
    Analyze the blog post and poll content for SEO optimization.
    Suggest improvements to increase visibility, including keyword optimization, metadata improvements, and content readability.
  expected_output: >
    A list of SEO recommendations and optimizations for better search engine ranking.
  agent: seo_optimizer

content_drafting_task:
  description: >
    current_year: {current_year}
    ###
    Draft detailed and professional content for both the posts and polls.
    The post should be well-structured with an introduction, body, and conclusion.
    The poll should include a concise question with 4 options, formatted for social media.
  expected_output: >
    A fully drafted and polished post in markdown or plain text, ready for publication.
    A finalized poll with the question and options, ready for posting.
  agent: content_drafter

twitter_post_creation_task:
  description: >
    current_year: {current_year}
    ###
    Create an engaging and concise post for Twitter based on the structured content.
    Ensure the post fits within the 249-character limit and resonates with the audience.
  expected_output: |
    {
      "Twitter_Post": {
        "tweet_text": "<Concise and engaging tweet (max 280 chars)>"
      }
    }
  output_file: twitter_post.json
  agent: twitter_post_creator

poll_creation_task:
  description: >
    current_year: {current_year}
    ###
    Create a social media poll based on the structured content, formatted for both Twitter and LinkedIn.
    Ensure the poll question is clear, concise, and relevant to the audience.
  expected_output: |
    {
      "Twitter_Poll": {
        "tweet_text": "<Poll tweet with call to action and relevant hashtags>",
        "poll_question": "<Clear poll question for Twitter>",
        "poll_options": ["Option 1", "Option 2", "Option 3", "Option 4"]
      },
      "LinkedIn_Poll": {
        "post_text": "<Professional LinkedIn post with CTA and hashtags>",
        "poll_question": "<Clear poll question for LinkedIn>",
        "poll_options": ["Option 1", "Option 2", "Option 3", "Option 4"]
      }
    }
  output_file: poll.json
  agent: poll_creator

linkedin_post_creation_task:
  description: >
    current_year: {current_year}
    ###
    Create a professional, engaging post for LinkedIn based on the structured content.
    Ensure the post resonates with a business-oriented audience and maintains a professional tone.
  expected_output: |
    {
      "LinkedIn_Post": {
        "post_text": "<Well-written LinkedIn post, including hashtags and CTA>"
      }
    }
  output_file: linkdin_post.json
  agent: linkedin_post_creator
